name: futbolito_app
description: sains.com

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_maps_flutter: ^0.5.13
  crypto: ^2.0.6
  cupertino_icons: ^0.1.2
  http: any
  shared_preferences: ^0.5.3+1
  font_awesome_flutter: ^8.4.0
  flutter_datetime_picker: ^1.2.5
  intl: ^0.15.8
  rflutter_alert: ^1.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/icon/
    - assets/images/
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat/Montserrat-Regular.ttf
        - asset: fonts/Montserrat/Montserrat-Italic.ttf
          style: italic
        - asset: fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700